/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.neurosky.mindwavemobiledemo;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
        public static final int btn_reset_height=0x7f060006;
        public static final int but_mood_marginLeft=0x7f060025;
        public static final int but_mood_marginTop=0x7f060026;
        public static final int but_state_connect_height=0x7f060007;
        /**  cardioplot bar 
         */
        public static final int cardioplot_bar_height=0x7f060005;
        public static final int cicle_view_radius=0x7f060004;
        public static final int cicle_view_x=0x7f060002;
        public static final int cicle_view_y=0x7f060003;
        public static final int counter_text_height=0x7f060014;
        public static final int counter_text_marginTop=0x7f060015;
        public static final int counter_text_size=0x7f060016;
        /**  datas 
         */
        public static final int datas_marginTop=0x7f06000c;
        public static final int habpm_text_marginLeft=0x7f06000f;
        public static final int hrv_countdown_marginTop=0x7f060013;
        public static final int hrv_countdown_width=0x7f060012;
        public static final int hrv_text_marginLeft=0x7f060011;
        public static final int lin_height=0x7f06000a;
        public static final int lin_marginLeft=0x7f06000b;
        /**  lin 
         */
        public static final int lin_marginTop=0x7f060008;
        public static final int lin_width=0x7f060009;
        public static final int pluse_height=0x7f06001b;
        public static final int pluse_marginRight=0x7f06001c;
        public static final int pluse_marginTop=0x7f06001d;
        /**  Plus 
         */
        public static final int pluse_width=0x7f06001a;
        public static final int progress_bg_height=0x7f06001f;
        public static final int progress_bg_marginBottom=0x7f060020;
        public static final int progress_bg_marginLeft=0x7f060021;
        /**  Mood 
         */
        public static final int progress_bg_width=0x7f06001e;
        public static final int r2rinterval_text_marginLeft=0x7f060010;
        public static final int rel_height=0x7f060023;
        public static final int rel_marginLeft=0x7f060024;
        public static final int rel_width=0x7f060022;
        public static final int text_size=0x7f06000e;
        public static final int text_width=0x7f06000d;
        public static final int version_info_marginBottom=0x7f060019;
        public static final int version_info_marginRight=0x7f060018;
        /**  Version info 
         */
        public static final int version_info_text_size=0x7f060017;
    }
    public static final class drawable {
        public static final int gouxuan1=0x7f020000;
        public static final int gouxuan2=0x7f020001;
        public static final int ic_launcher=0x7f020002;
        public static final int select_device_bg=0x7f020003;
    }
    public static final class id {
        public static final int AbsoluteLayout1=0x7f090000;
        public static final int Layout1=0x7f090027;
        public static final int btn_adapter=0x7f09002b;
        public static final int btn_device=0x7f09002d;
        public static final int btn_filedemo=0x7f090029;
        public static final int btn_selectdevice=0x7f09001a;
        public static final int btn_start=0x7f09000a;
        public static final int btn_stop=0x7f090012;
        public static final int device_name=0x7f090026;
        public static final int img1=0x7f090024;
        public static final int img2=0x7f090025;
        public static final int list_select=0x7f090023;
        public static final int tableLayout1=0x7f090001;
        public static final int tableRow1=0x7f090002;
        public static final int tableRow2=0x7f09000b;
        public static final int tableRow3=0x7f090013;
        public static final int tableRow4=0x7f09001b;
        public static final int tv_adapter=0x7f09002a;
        public static final int tv_attention=0x7f090006;
        public static final int tv_attention_label=0x7f090005;
        public static final int tv_badpacket=0x7f090021;
        public static final int tv_badpacket_label=0x7f090020;
        public static final int tv_delta=0x7f09000d;
        public static final int tv_delta_label=0x7f09000c;
        public static final int tv_device=0x7f09002c;
        public static final int tv_filedemo=0x7f090028;
        public static final int tv_highalpha=0x7f090015;
        public static final int tv_highalpha_label=0x7f090014;
        public static final int tv_highbeta=0x7f090019;
        public static final int tv_highbeta_label=0x7f090018;
        public static final int tv_lowalpha=0x7f090011;
        public static final int tv_lowalpha_label=0x7f090010;
        public static final int tv_lowbeta=0x7f090017;
        public static final int tv_lowbeta_label=0x7f090016;
        public static final int tv_lowgamma=0x7f09001d;
        public static final int tv_lowgamma_label=0x7f09001c;
        public static final int tv_meditation=0x7f090009;
        public static final int tv_meditation_label=0x7f090008;
        public static final int tv_middlegamma=0x7f09001f;
        public static final int tv_middlegamma_label=0x7f09001e;
        public static final int tv_ps=0x7f090004;
        public static final int tv_ps_lable=0x7f090003;
        public static final int tv_r2r_label=0x7f090007;
        public static final int tv_theta=0x7f09000f;
        public static final int tv_theta_label=0x7f09000e;
        public static final int wave_layout=0x7f090022;
    }
    public static final class layout {
        public static final int bluetoothdevice_view=0x7f030000;
        public static final int dialog_select_device=0x7f030001;
        public static final int first_view=0x7f030002;
        public static final int listitem_device=0x7f030003;
        public static final int main_view=0x7f030004;
    }
    public static final class raw {
        public static final int tgam_capture=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f070000;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f080000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f080001;
        public static final int dialog1=0x7f080002;
    }
    public static final class xml {
        public static final int sharp=0x7f040000;
    }
}
